## Import PyTorch

In [1]:
import torch

## Torch!

In [5]:
t = torch.Tensor(2, 3, 4)
type(t)

torch.Tensor

In [8]:
t.size()

torch.Size([2, 3, 4])

In [9]:
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [11]:
# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [12]:
t

tensor([[[-8.4352e-32,  4.5588e-41,  9.0596e-36,  0.0000e+00],
         [-4.8264e+14,  4.5587e-41, -4.8265e+14,  4.5587e-41],
         [-4.8264e+14,  4.5587e-41, -4.8267e+14,  4.5587e-41]],

        [[-4.8267e+14,  4.5587e-41, -4.8266e+14,  4.5587e-41],
         [-4.8255e+14,  4.5587e-41, -4.8257e+14,  4.5587e-41],
         [-4.8430e+14,  4.5587e-41,  1.8077e-43,  0.0000e+00]]])

In [18]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t.random_(10)

tensor([[[9., 4., 8., 0.],
         [5., 7., 3., 1.],
         [0., 7., 7., 0.]],

        [[8., 4., 0., 3.],
         [3., 9., 2., 6.],
         [8., 3., 4., 7.]]])

In [19]:
t

tensor([[[9., 4., 8., 0.],
         [5., 7., 3., 1.],
         [0., 7., 7., 0.]],

        [[8., 4., 0., 3.],
         [3., 9., 2., 6.],
         [8., 3., 4., 7.]]])

In [20]:
r = torch.Tensor(t)
r.resize_(3, 8)
r

tensor([[9., 4., 8., 0., 5., 7., 3., 1.],
        [0., 7., 7., 0., 8., 4., 0., 3.],
        [3., 9., 2., 6., 8., 3., 4., 7.]])

In [21]:
t

tensor([[[9., 4., 8., 0.],
         [5., 7., 3., 1.],
         [0., 7., 7., 0.]],

        [[8., 4., 0., 3.],
         [3., 9., 2., 6.],
         [8., 3., 4., 7.]]])

In [22]:
r.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
t

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
s = r.clone()

In [25]:
s

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
s.fill_(1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
r

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

## Vectors (1D Tensors)

In [29]:
v = torch.Tensor([1, 2, 3, 4])
v

tensor([1., 2., 3., 4.])

In [30]:
print(f"dim: {v.dim()}, size: {v.size()}")

dim: 1, size: torch.Size([4])


In [31]:
w = torch.Tensor([1, 0, 2, 0])
w

tensor([1., 0., 2., 0.])

In [33]:
# element wise multiplication
v*w

tensor([1., 0., 6., 0.])

In [34]:
#Scalar product
v @ w

tensor(7.)

In [36]:
x = torch.Tensor(5).random_(10)
x

tensor([2., 6., 0., 0., 7.])

In [39]:
print(f"first:{x[0]}, last:{x[-1]}")

first:2.0, last:7.0


In [41]:
x[1:3]

tensor([6., 0.])

In [42]:
v = torch.arange(1, 5)
v

tensor([1, 2, 3, 4])

In [46]:
u = torch.linspace(0, 10, 11)
u

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
print(u.pow(2), u)

tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.]) tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


## Matrices(2D Tensors)

In [49]:
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [50]:
m.dim()

2

In [51]:
print(m.size(0), m.size(1), m.size(), sep='----')

2----4----torch.Size([2, 4])


In [52]:
m.numel()

8

## Constructors

Same as numpy

## Casting

In [55]:
torch.*Tensor?

torch.BFloat16Tensor
torch.BoolTensor
torch.ByteTensor
torch.CharTensor
torch.DoubleTensor
torch.FloatTensor
torch.HalfTensor
torch.IntTensor
torch.LongTensor
torch.ShortTensor
torch.Tensor

In [60]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [56]:
m_double = m.double()

In [58]:
m_double

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]], dtype=torch.float64)

In [59]:
m_byte = m.byte()
m_byte

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]], dtype=torch.uint8)

In [62]:
# Move your tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
m.to(device)

cuda:0


tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]], device='cuda:0')

In [63]:
m_np = m.numpy()
m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)